name: update_submodules

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Make sure to check out the sub-module

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Check if changes were made
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes were made."
          else
            echo "Changes were made."
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions - update submodules"
            git add .
            git commit -m 'Update submodule'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.my_GITHUB_TOKEN }}